// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package trng_data_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 2;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    logic [31:0] d;
  } trng_data_hw2reg_trng_dout_reg_t;

  // HW -> register type
  typedef struct packed {
    trng_data_hw2reg_trng_dout_reg_t trng_dout; // [31:0]
  } trng_data_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] TRNG_DATA_TRNG_DOUT_OFFSET = 2'h 0;

  // Reset values for hwext registers and their fields
  parameter logic [31:0] TRNG_DATA_TRNG_DOUT_RESVAL = 32'h 0;

  // Register index
  typedef enum int {
    TRNG_DATA_TRNG_DOUT
  } trng_data_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] TRNG_DATA_PERMIT [1] = '{
    4'b 1111  // index[0] TRNG_DATA_TRNG_DOUT
  };

endpackage

