// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package trng_keccak_ctrl_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 3;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic        q;
    } trng_en;
    struct packed {
      logic        q;
    } keccak_en;
    struct packed {
      logic        q;
    } conditioning;
    struct packed {
      logic        q;
    } ack_key_read;
  } trng_keccak_ctrl_reg2hw_ctrl_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
      logic        de;
    } keccak;
    struct packed {
      logic        d;
      logic        de;
    } trng;
  } trng_keccak_ctrl_hw2reg_status_reg_t;

  // Register -> HW type
  typedef struct packed {
    trng_keccak_ctrl_reg2hw_ctrl_reg_t ctrl; // [3:0]
  } trng_keccak_ctrl_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    trng_keccak_ctrl_hw2reg_status_reg_t status; // [3:0]
  } trng_keccak_ctrl_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] TRNG_KECCAK_CTRL_CTRL_OFFSET = 3'h 0;
  parameter logic [BlockAw-1:0] TRNG_KECCAK_CTRL_STATUS_OFFSET = 3'h 4;

  // Register index
  typedef enum int {
    TRNG_KECCAK_CTRL_CTRL,
    TRNG_KECCAK_CTRL_STATUS
  } trng_keccak_ctrl_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] TRNG_KECCAK_CTRL_PERMIT [2] = '{
    4'b 0001, // index[0] TRNG_KECCAK_CTRL_CTRL
    4'b 0001  // index[1] TRNG_KECCAK_CTRL_STATUS
  };

endpackage

